### PR TITLE
Tests, TypeScript, Encoding, and Promise-based API

### PR DESCRIPTION
**Pull request by adamvoss**
@laktak This is a spare time project so I don't know how soon I will finish it, but it is at a point where you can get a good enough idea of where I am going.  I am opening this PR hoping for some early feedback on whether this is even something you would want so I have a better idea what to do with it when I do have it release ready.  I totally understand it may not be what you want for `any-json`, in which case I will release it as its own package.

On the API side, it is a re-write that is strictly `Promise` based (no more Async vs non-async members exposed) and supports encoding as well as decoding.

The command-line application could be modified to use this API.  I think that least some of the old API methods could be written in terms of these if it were really wanted.

### CODE REVIEW

**Comment by laktak** [comment]
Wow, that's quite a rewrite :)

I like what you are doing but I need to ask if this is a one-off PR? If you are OK with maintaining this for longer and looking after your changes I can add you as a collaborator with commit rights.

**Comment by adamvoss** [comment]
The short answer is yes I would be able to help with maintenance.

The risk, or my apprehension, is that my needs may not needs may not directly match your needs or desired stability, so some coordination will be needed (making me hesitant to want to commit directly) or at least I will need a clear understanding of what is/is not important to preserve.  For example, I would have no hesitation with switching one of the underlying format implementation libraries if it would fix an issue.  However, doing could be considered a breaking-change by some because it might change the output format or risk some other edge case being handled differently.

The longer answer is, I have a number of use cases where I need **any-json** or something like it; though most are API access, and not command line:

- I depend of **any-json** in [**pajv**](with https://www.npmjs.com/package/pajv) so have an interest in it being maintained.
   - I will at least attempt adding TOML support to any-json for this reason.
- I have a project where I want to be able to go back-and-forth between individual YAML files and a single csv (Jekyll currently requires one source file to one output page)
- I have a project where I want to be able to process, a likely multi-tabed spreadsheet into JSON/YAML file(s) (Again for a Jekyll website, but a single page)

The first of getting this to have sufficient parity to merge then adding TOML support is my highest priority.  Then I will dig into how best process my files for conversion between the Object and Tabular formats.

**Comment by adamvoss** [comment]
Oh, and understanding of target platforms would also be important (if you care) since that would impact libraries that can be used as well as ECMAScript version to target.

**Comment by adamvoss** [comment]
Oh, hey, just noticed this in the command line help:

>  Currently unavailable/awaiting PR:
    xlsx: https://www.npmjs.com/package/xlsx
    xls:  https://www.npmjs.com/package/xlsjs
    xml:  https://www.npmjs.com/package/xml2js

Is that true?  I want to add those formats eventually, but they are also problematic so would defer if they currently don't work anyway.

**Comment by laktak** [comment]
I think most people just use the CLI - at least that was the intention for the tool. The readme only mentions to look up the js for the api. If possible I think the CLI parameters should be kept compatible.

I don't have plans at the moment for any-json so I think it's better to have some breaking changes than to have it become obsolete. If you'd rather do this in your own repo I can mark this obsolete and include a link.

As for versions/targets etc. - I think maintaining < ES6 makes no sense for a nodejs project.

**Comment by adamvoss** [comment]
Thanks for being receptive and responsive to this!

> If possible I think the CLI parameters should be kept compatible.

I'm willing to provide a legacy parsing facility that would make the old parameters work.  However, the one holdout I have is the `-opt` parameter.  I really don't want to directly expose the underlying library's options configuration because doing so lessens the abstraction **any-json** provides, making it much more difficult to change an underlying library if there is ever a want/need.  I'm fine adding more options to support things, I just would want to build a layer of indirection to decouple in interface from the underlying type (and hopefully only expose a minimum surface area of configuration).

If supporting everything other than `-opt` is an acceptable compromise, I will get on implementing that and I think we can move forward.

> I don't have plans at the moment for any-json so I think it's better to have some breaking changes than to have it become obsolete.

I prefer not to needlessly create competing libraries which is why I have pursued "upstreaming" this even though it is well outside of what I would normally consider appropriate for a PR (tbh, I didn't realize how deep I would go when I started).

If we fork, I expect my fork would be used by the things I build on it, which from a public standpoint is probably just [pajv](https://www.npmjs.com/package/pajv).  Honestly, **any-json** is important tool but still a bit of a "niche" area so I am not sure how many direct users I would end up with, or if people are more likely to find the more established **any-json**.

> If you'd rather do this in your own repo I can mark this obsolete and include a link.

If we agree on a point where this can be merged, it would be good to then have more access so I can merge new features without needing to take up your time.  Also, things like Travis CI and npm publishing will need to be set up, I'm fine taking on all that work but it will take some coordination on permissions.  I'd be find working out of a repository under your user.  Though, as an alternative to moving development to a repository under my user (assuming the non-forked scenario), I would propose moving this repo to an organization (so issues are carried over) and we both would have access (@json-schema-everywhere would be an option, or it looks like @any-json is available for creation).

> As for versions/targets etc. - I think maintaining < ES6 makes no sense for a nodejs project.

Cool, someday if I am feeling adventurous, I might look at making it run in a web browser (most of the pieces support it), but I really wasn't looking forward to learning how to do that right at this moment.

**Comment by laktak** [comment]
> Thanks for being receptive and responsive to this!

It seems that you are doing all the work at the moment so the least I can do is support you with this.

> If supporting everything other than -opt is an acceptable compromise, I will get on implementing that and I think we can move forward.

I'm OK with that. I only added it because I wasn't sure of the use cases of the different formats. 

> I prefer not to needlessly create competing libraries which is why I have pursued "upstreaming" this even though it is well outside of what I would normally consider appropriate for a PR (tbh, I didn't realize how deep I would go when I started).

I have to admit that I was a bit surprised by your PR :)

> If we agree on a point where this can be merged, it would be good to then have more access so I can merge new features without needing to take up your time. Also, things like Travis CI and npm publishing will need to be set up, I'm fine taking on all that work but it will take some coordination on permissions. I'd be find working out of a repository under your user. Though, as an alternative to moving development to a repository under my user (assuming the non-forked scenario), I would propose moving this repo to an organization (so issues are carried over) and we both would have access (@json-schema-everywhere would be an option, or it looks like @any-json is available for creation).

Sounds great - if it's OK for you I'll move this to @any-json, give you equal permissions and connect Travis. I've never done this for npm but I guess it should be possible to transfer the package to a new user?

**Comment by adamvoss** [comment]
> I'm OK with that. I only added it because I wasn't sure of the use cases of the different formats.

Sweet!! I'll put building that on my TODO list.  I expect I will be able to get to it sometime this week.

> I have to admit that I was a bit surprised by your PR :)
 
The beginnings were humbler (#3, #4), but by the time I realized where I was going I recognized there was no point supporting those PRs if I ended up forked anyway :)

>  Sounds great - if it's OK for you I'll move this to @any-json, give you equal permissions and connect Travis. I've never done this for npm but I guess it should be possible to transfer the package to a new user?

Works for me! With **npm**, the repository link will need to be changed in package.json, but if if you use GitHub's move functionality, a redirect will be set up for the current url so nothing will be broken.  We will just want to make sure to change the URL for the next release.

Regarding transferring the npm package, I don't think that will be necessary.  If you sign in to NPM and go to the [any-json](https://www.npmjs.com/package/any-json) page you should be able to add me as a Collaborator on the right-hand side.  I am adamvoss there too and [this is my user page](https://www.npmjs.com/~adamvoss) if it happens to need that.

**Comment by laktak** [comment]
I've created any-json and moved the repo. You should have received an invite.

Travis should work (https://travis-ci.org/any-json/any-json) but doesn't show PRs yet (maybe on the next commit).

I've also added you on npm. Let me know if you run into any troubles!

**Comment by laktak** [comment]
I created a classic branch so you can merge to master when you are ready.

**Comment by adamvoss** [comment]
@laktak, I added the legacy argument parsing so merged it since you said that was okay.  All that it _should_ take (can't test with out actually releasing) to publish to npm is to push `3.0.0` tag at the current HEAD, but I held off in case you wanted to review or check anything before it gets released.

**Comment by laktak** [comment]
Hi Adam! The classic version was able to processes stdin, when you specified a format:

```
echo '{key:1}'|node out/lib/run.js -format=hjson
too few arguments: please specify the file to convert
for help use 'any-json -?
```

Would it be possible to add that back in before you publish?

Otherwise I think it looks good! Thanks!

**Pull request merged**
